USE [master]
GO

/****** Object:  Database [mydemodb]    Script Date: 09/09/2021 6:04:26 PM ******/
CREATE DATABASE [mydemodb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mydemodb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL\MSSQL\DATA\mydemodb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mydemodb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQL\MSSQL\DATA\mydemodb_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mydemodb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mydemodb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mydemodb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mydemodb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mydemodb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mydemodb] SET ARITHABORT OFF 
GO

ALTER DATABASE [mydemodb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mydemodb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mydemodb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mydemodb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mydemodb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mydemodb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mydemodb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mydemodb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mydemodb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mydemodb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [mydemodb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mydemodb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mydemodb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mydemodb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mydemodb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mydemodb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mydemodb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mydemodb] SET RECOVERY FULL 
GO

ALTER DATABASE [mydemodb] SET  MULTI_USER 
GO

ALTER DATABASE [mydemodb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mydemodb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mydemodb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mydemodb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [mydemodb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mydemodb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [mydemodb] SET  READ_WRITE 
GO

